parameters:
    sdrost.state_machine.factory.class: SDrost\StateMachineBundle\Factory\Factory
    sdrost.state_machine.array_loader.class: SDrost\StateMachineBundle\Loader\ArrayLoader
    sdrost.state_machine.class: SDrost\StateMachineBundle\StateMachine\ExtendedStateMachine
    sdrost.state_machine.callback_handler.class: Finite\Event\CallbackHandler
    sdrost.state_machine.callback_builder_facotry.class: Finite\Event\Callback\CallbackBuilderFactory

services:
    sdrost.state_machine.factory:
        class: %sdrost.state_machine.factory.class%
        arguments: [ "@service_container", 'sdrost.state_machine' ]

    sdrost.state_machine.callback_builder_facotry:
            class:      %sdrost.state_machine.callback_builder_facotry.class%

    sdrost.state_machine.callback_handler:
            class:      %sdrost.state_machine.callback_handler.class%
            arguments:  [ "@event_dispatcher" ]

    sdrost.state_machine.array_loader:
        class:      %sdrost.state_machine.array_loader.class%
        arguments:  [ ~ , @sdrost.state_machine.callback_handler, @sdrost.state_machine.callback_builder_facotry]
        public:     false

    sdrost.state_machine:
        class:      %sdrost.state_machine.class%
        arguments:  [ ~, "@event_dispatcher" ]
        # will be flagged In the KPhoenDoctrineStateMachineExtension as
        # "scope: prototype" or "shared: false", according to the current
        # Symfony version
