parameters:
    sdrost.state_machine.factory.class: SDrost\StateMachineBundle\Factory\Factory
    sdrost.state_machine.array_loader.class: Finite\Loader\ArrayLoader
    sdrost.state_machine.class: SDrost\StateMachineBundle\StateMachine\ExtendedStateMachine

services:
    sdrost.state_machine.factory:
        class: %domtain.state_machine.factory.class%
        arguments: [ "@service_container", 'sdrost.state_machine' ]

    sdrost.state_machine.array_loader:
        class:      %domtain.state_machine.array_loader.class%
        arguments:  [ ~ ]
        public:     false

    sdrost.state_machine:
        class:      %domtain.state_machine.class%
        arguments:  [ ~, "@event_dispatcher" ]
        # will be flagged In the KPhoenDoctrineStateMachineExtension as
        # "scope: prototype" or "shared: false", according to the current
        # Symfony version
