parameters:
    sdrost.state_machine.listener.persistence.class: SDrost\StateMachineBundle\Listener\Doctrine\PersistenceListener
    sdrost.state_machine.listener.injection.class: SDrost\StateMachineBundle\Listener\InjectionListener
    sdrost.state_machine.listener.callbacks.class: SDrost\StateMachineBundle\Listener\Doctrine\StatefulEntitiesCallbacksListener

services:
    # doctrine listeners
    sdrost.state_machine.listener.persistence:
        class:      %sdrost.state_machine.listener.persistence.class%
        arguments:  [ "@sdrost.state_machine.factory" ]
        tags:
            - { name: doctrine.event_subscriber }

    sdrost.state_machine.listener.injection:
        class:      %sdrost.state_machine.listener.injection.class%
        arguments:  [ "@sdrost.state_machine.factory" ]
        tags:
            - { name: doctrine.event_subscriber }
            - { name: jms_serializer.event_listener, event: serializer.post_deserialize, method: onPostDeserialize }

    # finite listeners
    sdrost.state_machine.listener.callbacks:
        class:      %sdrost.state_machine.listener.callbacks.class%
        tags:
            - { name: kernel.event_subscriber }
